name: AdlerMarketing
favicon: null
layout_spectrum: 0.26586
typography_spectrum: 0.7913277971092612
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9d9c98'
    - '#694835'
    - '#3a1f14'
    - '#cacbc6'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
