name: AdlerMarketing
favicon: null
layout_spectrum: 0.49071
typography_spectrum: 0.7913277971092612
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9d9c98'
    - '#694835'
    - '#3a1f14'
    - '#cacbc6'
  brandStrength: 0.5485836195293814
  lightness: 0.9118241963442415
  saturation: 0.2557463673874736
  rhythmicContrast: 0.19446240458637476
purpose: []
